FROM frickeldave/alpine:latest

LABEL MAINTAINER="David Koenig <dave@frickeldave.de>"

ARG IMAGE_NAME=frickeldave/nginx
ARG IMAGE_VERSION=1.1
ARG NGX_VERSION=1.17.6

RUN apk update \
	&& apk --no-cache add openssl \
	#build-deps \
	build-base \
	zlib-dev \
	pcre-dev \
	libressl-dev \
	pcre \
	libbz2 \
	libressl \
	&& rm -rf /var/lib/apt/lists/* \
	&& rm -rf /var/cache/apk/*

RUN mkdir /home/appuser/app/nginx \
	&& mkdir /home/appuser/app/nginx/client_temp \
	&& mkdir /home/appuser/app/nginx/proyx_temp \
	&& mkdir /home/appuser/app/nginx/fastcgi_temp \
	&& mkdir /home/appuser/app/nginx/uwsgi_temp \
	&& mkdir /home/appuser/app/nginx/scgi_temp \
	&& touch /home/appuser/app/nginx/nginx.pid \
	&& touch /home/appuser/app/nginx/nginx.lock \
	&& mkdir /home/appuser/data/nginx \
	&& mkdir /home/appuser/data/nginx/log \
	&& mkdir /home/appuser/data/nginx/conf.d \
	&& mkdir /home/appuser/data/nginx/html

COPY ./setup/nginx.cnf /home/appuser/data/nginx/nginx.cnf
COPY ./setup/conf.d/nginx_init.conf /home/appuser/data/nginx/conf.d
COPY ./setup/start.sh /home/appuser/app/nginx/start.sh
COPY ./setup/index.html /home/appuser/data/nginx/html/index.html

RUN cd /home/appuser/app/nginx \
	&& curl https://nginx.org/download/nginx-$NGX_VERSION.tar.gz --progress-bar | tar xzf - \
	&& mv nginx-* /home/appuser/app/nginx-install
	
RUN cd /home/appuser/app/nginx-install && ./configure \
       --prefix=/usr/share/nginx \
       --sbin-path=/usr/local/bin/nginx \
       --conf-path=/home/appuser/data/nginx/nginx.cnf \
       --error-log-path=/home/appuser/data/nginx/log/nginx_error.log \
       --http-log-path=//home/appuser/data/nginx/log/nginx_http.log \
       --pid-path=/home/appuser/app/nginx/nginx.pid \
       --lock-path=/home/appuser/app/nginx/nginx.lock \
       --http-client-body-temp-path=/home/appuser/app/nginx/client_temp \
       --http-proxy-temp-path=/home/appuser/app/nginx/proxy_temp \
       --http-fastcgi-temp-path=/home/appuser/app/nginx/fastcgi_temp \
       --http-uwsgi-temp-path=/home/appuser/app/nginx/uwsgi_temp \
       --http-scgi-temp-path=/home/appuser/app/nginx/scgi_temp \
       --user=appuser \
       --group=appuser \
       --with-http_addition_module \
       --with-http_auth_request_module \
       --with-http_gunzip_module \
       --with-http_gzip_static_module \
       --with-http_realip_module \
       --with-http_ssl_module \
       --with-http_stub_status_module \
       --with-http_sub_module \
       --with-http_v2_module \
       --with-threads \
       --with-stream \
       --with-stream_ssl_module \
       --without-http_memcached_module \
       --without-mail_pop3_module \
       --without-mail_imap_module \
       --without-mail_smtp_module \
       --with-pcre-jit \
       --with-cc-opt='-g -O2 -fstack-protector-strong -Wformat -Werror=format-security' \
       --with-ld-opt='-Wl,-z,relro -Wl,--as-needed' \
	&& make install \
	&& cd /home/appuser/app \
	&& rm -rf /home/appuser/app/nginx-install

RUN chown -R appuser:appuser /home/appuser/data/nginx \
	&& chown -R appuser:appuser /home/appuser/app/nginx

USER appuser

ENTRYPOINT ["/home/appuser/app/nginx/start.sh"]